import type { Metadata } from "next";
import { Navbar } from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Terms of Use | ApnaVakil",
  description: "Simple terms of use for ApnaVakil.",
};

const sections = [
  {
    title: "1. What ApnaVakil Is",
    body: [
      "ApnaVakil is an AI legal assistance platform. It can help you understand legal topics, summarize documents, draft basic text, and prepare questions for a lawyer.",
      "ApnaVakil is not a law firm, lawyer, advocate, or court authority. Using ApnaVakil does not create a lawyer-client relationship.",
    ],
  },
  {
    title: "2. No Legal Advice Guarantee",
    body: [
      "The answers generated by ApnaVakil are for general information and support only. They may be incomplete, outdated, or incorrect.",
      "You should not rely only on ApnaVakil for legal, financial, tax, property, criminal, family, immigration, or court-related decisions. Always confirm important matters with a qualified lawyer.",
    ],
  },
  {
    title: "3. Your Responsibility",
    body: [
      "You are responsible for the questions, documents, facts, and information you provide. You must check all AI outputs before using them.",
      "You agree not to use ApnaVakil for illegal activity, fraud, harassment, harmful instructions, false evidence, or anything that violates another person's rights.",
    ],
  },
  {
    title: "4. Documents and Uploads",
    body: [
      "If you upload or share any document, you confirm that you have the right to use and share it.",
      "Do not upload highly sensitive information unless it is necessary. You are responsible for removing details you do not want processed.",
    ],
  },
  {
    title: "5. Account and Access",
    body: [
      "You are responsible for keeping your login details safe and for all activity under your account.",
      "We may suspend or stop access if the service is misused, used illegally, attacked, copied, or used in a way that may harm ApnaVakil or other users.",
    ],
  },
  {
    title: "6. Service Availability",
    body: [
      "We try to keep ApnaVakil available, but we do not promise that it will always work without delay, error, interruption, data loss, or security issue.",
      "Features may change, improve, pause, or be removed at any time.",
    ],
  },
  {
    title: "7. Limitation of Liability",
    body: [
      "To the maximum extent allowed by law, ApnaVakil and its owners, team, partners, and service providers are not responsible for losses caused by using, not using, or relying on the platform.",
      "This includes business loss, legal loss, missed deadlines, wrong filings, court issues, financial loss, data loss, or decisions made from AI-generated content.",
    ],
  },
  {
    title: "8. Changes to These Terms",
    body: [
      "We may update these terms when the product, law, or business changes. The latest version will be posted on this page.",
      "By continuing to use ApnaVakil after updates, you accept the updated terms.",
    ],
  },
];

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#0A0A0A] text-[#F5F5F5]">
      <Navbar eyebrow="Terms of Use" />
      <div className="mx-auto max-w-4xl px-6 py-12 sm:px-10">
        <section className="mb-10">
          <p className="text-sm font-medium text-[#A1A1AA]">Last updated: May 22, 2026</p>
          <h1 className="mt-4 font-display text-4xl font-semibold tracking-tight sm:text-5xl">
            Terms of Use
          </h1>
          <p className="mt-5 max-w-2xl text-base leading-7 text-[#A1A1AA]">
            These terms explain how you may use ApnaVakil. Please read them before using the
            platform.
          </p>
        </section>

        <div className="space-y-4">
          {sections.map((section) => (
            <section key={section.title} className="matte-card rounded-[1.5rem] p-6">
              <h2 className="font-display text-xl font-semibold tracking-tight">{section.title}</h2>
              <div className="mt-4 space-y-3">
                {section.body.map((paragraph) => (
                  <p key={paragraph} className="text-sm leading-7 text-[#A1A1AA]">
                    {paragraph}
                  </p>
                ))}
              </div>
            </section>
          ))}
        </div>
      </div>
    </main>
  );
}
